name: Validar e Gerar APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validar Arquivos
        uses: actions/checkout@v4

      - name: Configurar Ambiente Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validar Ferramentas (Auto-Instalação)
        run: |
          # Este comando ignora a falta da pasta 'gradle' e instala uma nova
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Executar Construção do APK
        run: gradle assembleDebug --stacktrace

      - name: Entrega do APK Validado
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-validado
          path: "**/*.apk"
